const $=s=>document.querySelector(s);const pages=[...document.querySelectorAll('.page')];const foods=['火锅','烤肉','寿司','日料','西餐','川菜','家常菜','韩餐','甜品'];const emojis=['🍲','🥩','🍣','🍱','🍝','🌶️','炒菜','🍜','🍰'];const pad=n=>String(n).padStart(2,'0');const localDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;let tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);$('#date').value=localDate(tomorrow);$('#date').min=localDate(new Date());let selected='',step=1,foodTimer,posterBlob,posterKey='',jump=0;const labels=['不要','再考虑下','点不到我','真的不要吗'];const corners=[0,3,1,2];
function selectedVisual(){const index=foods.indexOf(selected);return {label:selected,emoji:emojis[index],image:index===6?'../meal.png':null};}
function setStep(n){location.hash=String(n)}function render(){clearTimeout(foodTimer);let n=Number(location.hash.slice(1))||1;n=Math.max(1,Math.min(5,n));if(n===5&&!selected)n=4;step=n;pages.forEach((p,i)=>p.hidden=i!==n-1);$('#stepText').textContent=`0${n} / 05`;document.querySelectorAll('.progress i').forEach((p,i)=>{p.className=i===n-1?'current':i<n-1?'done':''});$('#back').setAttribute('aria-label',n===1?'重置邀约页':'返回上一页');if(n===1)requestAnimationFrame(positionNo);if(n===3)updateMin();if(n===5){$('#resultDate').textContent=dateLabel();$('#resultTime').textContent=$('#time').value;$('#resultFood').textContent=selected;const visual=selectedVisual();const art=$('#resultArt');art.setAttribute('aria-label',visual.label);art.replaceChildren();if(visual.image){const img=document.createElement('img');img.src=visual.image;img.alt='';art.append(img);}else{art.textContent=visual.emoji;}$('#saveStatus').textContent='保存这份安排，见面前看一眼。';$('#posterPreview').hidden=true;}window.scrollTo({top:0,behavior:'instant'});}window.addEventListener('hashchange',render);
$('#back').onclick=()=>{clearTimeout(foodTimer);if(step>1)setStep(step-1);else{jump=0;$('#playArea').classList.remove('escaped');$('#no').removeAttribute('style');$('#no').textContent=labels[0];}};$('#yes').onclick=()=>setStep(2);document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>setStep(+b.dataset.next));
function positionNo(){if(!jump)return;const area=$('#playArea'),btn=$('#no');if(!area.clientWidth)return;const corner=corners[(jump-1)%4];const right=Math.max(10,area.clientWidth-btn.offsetWidth-10),bottom=Math.max(10,area.clientHeight-btn.offsetHeight-10);btn.style.left=`${corner%2?right:10}px`;btn.style.top=`${corner>1?bottom:10}px`;}
$('#no').onclick=()=>{jump++;$('#no').textContent=labels[jump%4];$('#playArea').classList.add('escaped');positionNo();};new ResizeObserver(positionNo).observe($('#playArea'));window.addEventListener('resize',positionNo);
function updateMin(){const now=new Date();$('#date').min=localDate(now);if($('#date').value===localDate(now)){$('#time').min=`${pad(now.getHours())}:${pad(now.getMinutes())}`;}else $('#time').removeAttribute('min');}$('#date').onchange=()=>{updateMin();$('#dateError').textContent='';};$('#dateForm').onsubmit=e=>{e.preventDefault();updateMin();const d=new Date(`${$('#date').value}T${$('#time').value}:00`);if(!Number.isFinite(d.getTime())||d.getTime()<Date.now()){$('#dateError').textContent='请选择一个还没到来的见面时间。';return;}$('#dateError').textContent='';setStep(4);};
foods.forEach((f,i)=>{const b=document.createElement('button');b.className='food';b.setAttribute('aria-pressed','false');b.innerHTML=`<span class="check" aria-hidden="true">✓</span><span class="emoji" aria-hidden="true">${i===6?'<img class="food-art" src="../meal.png" alt="炒菜">':emojis[i]}</span><span>${f}</span>`;b.onclick=()=>{clearTimeout(foodTimer);selected=f;document.querySelectorAll('.food').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});foodTimer=setTimeout(()=>setStep(5),450);};$('#foods').append(b);});
function dateLabel(){const d=new Date(`${$('#date').value}T12:00:00`);return `${d.getMonth()+1}月${d.getDate()}日 · ${['周日','周一','周二','周三','周四','周五','周六'][d.getDay()]}`;}
async function makePoster(){const key=[$('#date').value,$('#time').value,selected].join('|');if(posterBlob&&posterKey===key)return posterBlob;await document.fonts.ready;const c=document.createElement('canvas');c.width=1080;c.height=1536;const ctx=c.getContext('2d');ctx.fillStyle='#eaf4ff';ctx.fillRect(0,0,1080,1536);ctx.fillStyle='#fcfeff';ctx.beginPath();ctx.roundRect(75,75,930,1386,45);ctx.fill();ctx.textAlign='center';const text=(s,y,size,color='#355976',font='sans-serif')=>{ctx.fillStyle=color;ctx.font=`${size}px ${font}`;ctx.fillText(s,540,y);};text('一 起 吃 饭 · 轻 松 聊 聊',155,27,'#6c8fab');const visual=selectedVisual();if(visual.image){const img=new Image();img.src=visual.image;await img.decode();ctx.drawImage(img,310,200,460,460);}else{ctx.save();ctx.font='330px "Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(visual.emoji,540,430);ctx.restore();}text('见面吧，就这么说定了。',755,53,'#355976','serif');text('好好吃饭，顺便聊聊最近。',825,29,'#6d8aa2');ctx.strokeStyle='#c7dfef';ctx.setLineDash([9,10]);ctx.beginPath();ctx.moveTo(135,910);ctx.lineTo(945,910);ctx.stroke();ctx.setLineDash([]);const rows=[['吃饭日期',`${$('#date').value.slice(0,4)}年 ${dateLabel()}`],['见面时间',$('#time').value],['一起去吃',selected]];rows.forEach(([k,v],i)=>{ctx.textAlign='left';ctx.font='30px sans-serif';ctx.fillStyle='#6888a4';ctx.fillText(k,170,1010+i*100);ctx.textAlign='right';ctx.fillStyle='#3c6080';ctx.font='34px sans-serif';ctx.fillText(v,910,1010+i*100);});ctx.textAlign='center';text('GOOD FOOD  ·  GOOD COMPANY',1370,25,'#779bb8');posterBlob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('生成失败')),'image/png'));posterKey=key;return posterBlob;}
let previewURL;function showPoster(blob){if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(blob);$('#posterImage').src=previewURL;$('#posterPreview').hidden=false;return previewURL;}
$('#save').onclick=async()=>{const b=$('#save');b.disabled=true;b.textContent='正在生成海报…';try{const blob=await makePoster();const url=showPoster(blob);const a=document.createElement('a');a.href=url;a.download=`约饭安排-${$('#date').value}.png`;a.click();$('#saveStatus').textContent='海报已生成；手机上也可以长按下方图片保存。';}catch(e){$('#saveStatus').textContent='海报暂时没有生成成功，请再试一次。';}finally{b.disabled=false;b.textContent='↓ 保存海报';}};
$('#share').onclick=async()=>{try{const blob=await makePoster();const file=new File([blob],'约饭安排.png',{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'约饭安排',text:`${dateLabel()} ${$('#time').value}，一起吃${selected}。`});}else{showPoster(blob);$('#saveStatus').textContent='长按下方海报保存，再发送给朋友。';}}catch(e){if(e.name!=='AbortError')$('#saveStatus').textContent='分享暂不可用，请使用“保存海报”。';}};render();
